name: Create and Start Release

on: [workflow_dispatch]

jobs:
    create-release:
      runs-on: ubuntu-latest
      steps:

        - name: Create & Start Release
          id: release
          uses: digital-ai/github-actions-release@main
          with:
            serverUrl: ${{ secrets.SERVERURL }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            templateId: 'Folder3f5cf31df154440495d8af9425aa9cdb/Releasec4e4b7bce46f4720a43ead5da8543086'

        - name: Get Release Data
          id: output
          run: echo ${{ steps.release.outputs.response }}
